### ISSUE TITLE
Unable to use the "max_results" command-line argument

### ISSUE THREAD

**Issue by Eustacio** [Eustacio/yelp-scraper#1]
Trying use the _max_results_ command-line argument results in the following error:

`Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/scrapy/core/engine.py", line 127, in _next_request
    request = next(slot.start_requests)
  File "/yelp-scraper/src/spiders/yelp.py", line 44, in start_requests
    if self._arguments_valid():
  File "yelp-scraper/src/spiders/yelp.py", line 86, in _arguments_valid
    return self.find and self.near and self.max_results >= 1
TypeError: '>=' not supported between instances of 'str' and 'int'
`

**Comment by Eustacio** [comment]
This issue was solved on commit ad2e447
